spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3000/usedmarket?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    resources:
      static-locations: classpath:/static/, classpath:/public/, D:/productImages/
    chain:
      cache: false;
      enabled: true;
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
      location: D:/productImages


kakaoAPI:
  url:
    login: https://kauth.kakao.com/oauth/authorize
    redirect: http://localhost:8080/kakao_login
    token: https://kauth.kakao.com/oauth/token
    logout: https://kapi.kakao.com/v1/user/logout
    userinfo: https://kapi.kakao.com/v2/user/me

  client:
    key: f03a345d8110bf027490e7b41a190876
